[project]
name = "pyview-map"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pyview-web>=0.8.3",
    "uvicorn>=0.41.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pyview_map"]

[project.scripts]
pyview-map = "pyview_map.__main__:main"
