[project]
name = "pyview-map"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pyview-web>=0.8.3",
    "uvicorn>=0.41.0",
    "fastapi>=0.115",
    "httpx>=0.28",
    "http-stream-transport",
    "http-stream-client",
    "jrpc-common",
]

[tool.uv.sources]
http-stream-transport = { git = "ssh://git@github.com/avilior/http_stream_prj", subdirectory = "packages/server_pkg" }
http-stream-client = { git = "ssh://git@github.com/avilior/http_stream_prj", subdirectory = "packages/client" }
jrpc-common = { git = "ssh://git@github.com/avilior/http_stream_prj", subdirectory = "packages/jrpc_common" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pyview_map"]

[project.scripts]
pyview-map = "pyview_map.__main__:main"
